name: Build EXE and attach to Release

on:
  release:
    types: [published]     # parte quando pubblichi una Release
  workflow_dispatch:       # fallback: puoi lanciarlo a mano
    inputs:
      tag:
        description: 'Tag della release (es: v1.1.2)'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || inputs.tag }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create spec file
        run: |
          echo "# -*- mode: python -*-
          block_cipher = None

          a = Analysis(
              ['src/main.py'],
              pathex=['src'],
              binaries=[],
              datas=[('src', 'src')],
              hiddenimports=['customtkinter', 'PIL', 'tkinter'],
              hookspath=[],
              hooksconfig={},
              runtime_hooks=[],
              excludes=[],
              win_no_prefer_redirects=False,
              win_private_assemblies=False,
              cipher=block_cipher,
              noarchive=False,
          )
          
          # Add customtkinter files
          import os
          import customtkinter
          ctk_path = os.path.dirname(customtkinter.__file__)
          a.datas += Tree(ctk_path, prefix='customtkinter', excludes=['*.py'])
          
          pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
          
          exe = EXE(
              pyz,
              a.scripts,
              a.binaries,
              a.zipfiles,
              a.datas,
              [],
              name='sapcar_unpacker',
              debug=False,
              bootloader_ignore_signals=False,
              strip=False,
              upx=True,
              upx_exclude=[],
              runtime_tmpdir=None,
              console=False,
              disable_windowed_traceback=False,
              target_arch=None,
              codesign_identity=None,
              entitlements_file=None,
          )" > sapcar_unpacker.spec

      - name: Build EXE (PyInstaller)
        run: |
          pyinstaller --clean sapcar_unpacker.spec
          
      - name: Test EXE launch
        run: |
          cd dist
          ./sapcar_unpacker.exe &
          Start-Sleep -s 5
          Get-Process sapcar_unpacker -ErrorAction SilentlyContinue | Stop-Process

      - name: List build outputs (debug)
        run: |
          echo "PWD:" $PWD
          dir
          echo "DIST:"
          dir dist

      - name: Upload EXE to the Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name || inputs.tag }}
          files: |
            dist/sapcar_unpacker.exe
          fail_on_unmatched_files: true
