name: Build EXE and attach to Release

on:
  release:
    types: [published]     # parte quando pubblichi una Release
  workflow_dispatch:       # fallback: puoi lanciarlo a mano
    inputs:
      tag:
        description: 'Tag della release (es: v1.1.2)'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || inputs.tag }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Syntax check
        run: python -m py_compile sapcar_unpacker.py

      - name: Install PyInstaller
        run: pip install --upgrade pip && pip install pyinstaller

      - name: Build EXE (PyInstaller)
        run: pyinstaller --onefile --noconsole --name sapcar_unpacker sapcar_unpacker.py

      - name: List build outputs (debug)
        run: |
          echo "PWD:" $PWD
          dir
          echo "DIST:"
          dir dist

      - name: Upload EXE to the Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name || inputs.tag }}
          files: |
            dist/sapcar_unpacker.exe
          fail_on_unmatched_files: true
